/**
 * 和风天气（QWeather）工具函数
 * 包含自有 Icon Code → {描述, emoji图标, 主题渐变色} 的映射
 * 图标代码表参考：https://dev.qweather.com/docs/resource/icons/
 */

// 和风天气 icon code（3 位字符串，带补零） → 信息
// 覆盖官方 100~116（晴-雾）、300~318（阵雨-强阵雨）、350~351（特殊雨）
// 399（特强雨）、400~499（雪及特殊雪）、500~509（沙尘/浮尘）
// 800~808（台风/热带气旋）、900~902（热/冷/大风通用告警）
// 999（未知）
const ICON_MAP = {
  // === 晴 ===
  '100': { desc: '晴', icon: '☀️', theme: 'clear' },
  '101': { desc: '多云', icon: '⛅', theme: 'cloud' },
  '102': { desc: '少云', icon: '🌤️', theme: 'cloud' },
  '103': { desc: '晴间多云', icon: '🌤️', theme: 'cloud' },
  '104': { desc: '阴', icon: '☁️', theme: 'cloud' },

  // === 风 ===
  '150': { desc: '有风', icon: '🌬️', theme: 'cloud' },
  '151': { desc: '北风', icon: '🌬️', theme: 'cloud' },
  '152': { desc: '东北风', icon: '🌬️', theme: 'cloud' },
  '153': { desc: '东风', icon: '🌬️', theme: 'cloud' },
  '154': { desc: '东南风', icon: '🌬️', theme: 'cloud' },
  '155': { desc: '南风', icon: '🌬️', theme: 'cloud' },
  '156': { desc: '西南风', icon: '🌬️', theme: 'cloud' },
  '157': { desc: '西风', icon: '🌬️', theme: 'cloud' },
  '158': { desc: '西北风', icon: '🌬️', theme: 'cloud' },

  // === 雾/霾 ===
  '500': { desc: '浮尘', icon: '🌫️', theme: 'fog' },
  '501': { desc: '扬沙', icon: '🌫️', theme: 'fog' },
  '502': { desc: '沙尘暴', icon: '💨', theme: 'fog' },
  '503': { desc: '强沙尘暴', icon: '💨', theme: 'fog' },
  '504': { desc: '浮尘', icon: '🌫️', theme: 'fog' },
  '507': { desc: '雾霾', icon: '🌫️', theme: 'fog' },
  '508': { desc: '霾', icon: '🌫️', theme: 'fog' },
  '509': { desc: '霾', icon: '🌫️', theme: 'fog' },

  // === 小雨/阵雨系列 ===
  '300': { desc: '阵雨', icon: '🌦️', theme: 'rain' },
  '301': { desc: '强阵雨', icon: '🌦️', theme: 'rain' },
  '302': { desc: '雷阵雨', icon: '⛈️', theme: 'storm' },
  '303': { desc: '强雷阵雨', icon: '⛈️', theme: 'storm' },
  '304': { desc: '雷阵雨伴有冰雹', icon: '⛈️', theme: 'storm' },
  '305': { desc: '小雨', icon: '🌦️', theme: 'rain' },
  '306': { desc: '中雨', icon: '🌧️', theme: 'rain' },
  '307': { desc: '大雨', icon: '🌧️', theme: 'rain' },
  '308': { desc: '极端降雨', icon: '🌧️', theme: 'rain' },
  '309': { desc: '小雨', icon: '🌧️', theme: 'rain' },
  '310': { desc: '暴雨', icon: '🌧️', theme: 'rain' },
  '311': { desc: '大暴雨', icon: '🌧️', theme: 'rain' },
  '312': { desc: '特大暴雨', icon: '🌧️', theme: 'rain' },
  '313': { desc: '冻雨', icon: '🌧️', theme: 'rain' },
  '314': { desc: '小雨到中雨', icon: '🌧️', theme: 'rain' },
  '315': { desc: '中雨到大雨', icon: '🌧️', theme: 'rain' },
  '316': { desc: '大雨到暴雨', icon: '🌧️', theme: 'rain' },
  '317': { desc: '暴雨到大暴雨', icon: '🌧️', theme: 'rain' },
  '318': { desc: '大暴雨到特大暴雨', icon: '🌧️', theme: 'rain' },
  '350': { desc: '阵雨', icon: '🌦️', theme: 'rain' },
  '351': { desc: '阵雨', icon: '🌦️', theme: 'rain' },
  '399': { desc: '雨', icon: '🌧️', theme: 'rain' },

  // === 雪 ===
  '400': { desc: '小雪', icon: '🌨️', theme: 'snow' },
  '401': { desc: '中雪', icon: '🌨️', theme: 'snow' },
  '402': { desc: '大雪', icon: '❄️', theme: 'snow' },
  '403': { desc: '暴雪', icon: '❄️', theme: 'snow' },
  '404': { desc: '雨夹雪', icon: '🌨️', theme: 'snow' },
  '405': { desc: '小到中雪', icon: '🌨️', theme: 'snow' },
  '406': { desc: '中到大雪', icon: '🌨️', theme: 'snow' },
  '407': { desc: '大到暴雪', icon: '❄️', theme: 'snow' },
  '408': { desc: '阵雪', icon: '🌨️', theme: 'snow' },
  '409': { desc: '小雪', icon: '🌨️', theme: 'snow' },
  '410': { desc: '中雪', icon: '🌨️', theme: 'snow' },
  '499': { desc: '雪', icon: '🌨️', theme: 'snow' },

  // === 热带气旋 / 台风 ===
  '800': { desc: '热带气旋（热带低压）', icon: '🌀', theme: 'storm' },
  '801': { desc: '热带气旋（热带风暴）', icon: '🌀', theme: 'storm' },
  '802': { desc: '强热带风暴', icon: '🌀', theme: 'storm' },
  '803': { desc: '台风', icon: '🌀', theme: 'storm' },
  '804': { desc: '强台风', icon: '🌀', theme: 'storm' },
  '805': { desc: '超强台风', icon: '🌀', theme: 'storm' },
  '806': { desc: '热带气旋（残余低压）', icon: '🌀', theme: 'storm' },
  '807': { desc: '飓风', icon: '🌀', theme: 'storm' },
  '808': { desc: '强烈热带气旋', icon: '🌀', theme: 'storm' },

  // === 温度/通用告警 ===
  '900': { desc: '热', icon: '🔥', theme: 'clear' },
  '901': { desc: '冷', icon: '🥶', theme: 'snow' },
  '902': { desc: '大风', icon: '🌪️', theme: 'storm' },

  // === 兜底 ===
  '999': { desc: '未知', icon: '❓', theme: 'cloud' },
}

const THEME_GRADIENTS = {
  clear: 'linear-gradient(135deg, #FFB347 0%, #FFCC70 50%, #FFE5B4 100%)',
  cloud: 'linear-gradient(135deg, #8E9EAB 0%, #A4B5C4 50%, #DBE6F0 100%)',
  fog:   'linear-gradient(135deg, #BDC3C7 0%, #C9D0D4 50%, #E8ECEF 100%)',
  rain:  'linear-gradient(135deg, #4B6CB7 0%, #506A85 50%, #8FA9C2 100%)',
  snow:  'linear-gradient(135deg, #83A4D4 0%, #B6C6DD 50%, #E0E8F0 100%)',
  storm: 'linear-gradient(135deg, #232526 0%, #414345 50%, #6B7071 100%)',
}

export function getIconInfo(code) {
  const key = String(code).padStart(3, '0')
  return ICON_MAP[key] ?? { desc: '未知', icon: '❓', theme: 'cloud' }
}

export function getThemeGradient(code) {
  const { theme } = getIconInfo(code)
  return THEME_GRADIENTS[theme] ?? THEME_GRADIENTS.cloud
}

export function formatDate(fxDate) {
  if (!fxDate) return { date: '--/--', weekday: '--' }
  const [y, m, d] = fxDate.split('-').map(Number)
  const date = new Date(y, m - 1, d)
  const mm = String(m).padStart(2, '0')
  const dd = String(d).padStart(2, '0')
  const weekdays = ['周日', '周一', '周二', '周三', '周四', '周五', '周六']
  return {
    date: `${mm}-${dd}`,
    weekday: weekdays[date.getDay()],
  }
}

export function uvCategory(level) {
  const n = Number(level)
  if (Number.isNaN(n)) return '无数据'
  if (n <= 2) return '弱'
  if (n <= 5) return '中'
  if (n <= 7) return '强'
  if (n <= 10) return '很强'
  return '极强'
}

export const QW_ERROR_MESSAGES = {
  '204': '此地区暂无天气数据',
  '400': '请求参数错误',
  '401': 'API Key 无效',
  '402': 'API 配额已用尽，请稍后重试',
  '403': '无访问权限',
  '404': '未找到该城市',
  '429': '请求过于频繁，请稍后重试',
  '500': '服务异常，请稍后重试',
  '502': '无法连接和风天气服务，请确认代理运行中',
}

// ============================================================
// 地名翻译表（覆盖全球国家/省州/城市，含本地语言拼写）
// ============================================================

/** 国家名翻译：英文官方名 + 本地语言名（日/韩/俄/越/阿/法/西/葡等） */
const COUNTRY_ZH = {
  // 中文
  '中国': '中国', '中华人民共和国': '中国',
  // 亚洲
  'China': '中国', '日本': '日本', 'Japan': '日本', 'Nihon': '日本', 'Nippon': '日本',
  'South Korea': '韩国', 'Republic of Korea': '韩国', 'Korea': '韩国', '대한민국': '韩国',
  'North Korea': '朝鲜', 'Democratic People\'s Republic of Korea': '朝鲜',
  'Mongolia': '蒙古',
  'Vietnam': '越南', 'Việt Nam': '越南', 'Viet Nam': '越南',
  'Thailand': '泰国',
  'Singapore': '新加坡',
  'Malaysia': '马来西亚',
  'Indonesia': '印度尼西亚',
  'Philippines': '菲律宾',
  'Myanmar': '缅甸',
  'Cambodia': '柬埔寨',
  'Laos': '老挝',
  'India': '印度', 'भारत': '印度',
  'Nepal': '尼泊尔',
  'Sri Lanka': '斯里兰卡',
  'Bangladesh': '孟加拉国',
  'Pakistan': '巴基斯坦',
  'Maldives': '马尔代夫',
  'Bhutan': '不丹',
  'Afghanistan': '阿富汗',
  'Iran': '伊朗',
  'Iraq': '伊拉克',
  'Saudi Arabia': '沙特阿拉伯',
  'United Arab Emirates': '阿联酋',
  'Qatar': '卡塔尔',
  'Kuwait': '科威特',
  'Bahrain': '巴林',
  'Oman': '阿曼',
  'Yemen': '也门',
  'Jordan': '约旦',
  'Syria': '叙利亚',
  'Lebanon': '黎巴嫩',
  'Israel': '以色列',
  'Palestine': '巴勒斯坦',
  // 中亚
  'Turkey': '土耳其', 'Türkiye': '土耳其',
  'Cyprus': '塞浦路斯',
  'Georgia': '格鲁吉亚',
  'Armenia': '亚美尼亚',
  'Azerbaijan': '阿塞拜疆',
  'Kazakhstan': '哈萨克斯坦',
  'Uzbekistan': '乌兹别克斯坦',
  'Kyrgyzstan': '吉尔吉斯斯坦',
  'Tajikistan': '塔吉克斯坦',
  'Turkmenistan': '土库曼斯坦',
  // 欧洲
  'Russia': '俄罗斯', 'Russian Federation': '俄罗斯', 'Россия': '俄罗斯',
  'Ukraine': '乌克兰',
  'Belarus': '白俄罗斯',
  'Poland': '波兰', 'Polska': '波兰',
  'Germany': '德国', 'Deutschland': '德国',
  'France': '法国',
  'Netherlands': '荷兰', 'Holland': '荷兰',
  'Belgium': '比利时',
  'Luxembourg': '卢森堡',
  'Switzerland': '瑞士',
  'Austria': '奥地利',
  'Italy': '意大利', 'Italia': '意大利',
  'Spain': '西班牙', 'España': '西班牙',
  'Portugal': '葡萄牙',
  'Greece': '希腊',
  'Czech Republic': '捷克', 'Czechia': '捷克',
  'Slovakia': '斯洛伐克',
  'Hungary': '匈牙利', 'Magyarország': '匈牙利',
  'Slovenia': '斯洛文尼亚',
  'Croatia': '克罗地亚',
  'Bosnia and Herzegovina': '波黑',
  'Serbia': '塞尔维亚',
  'Montenegro': '黑山',
  'North Macedonia': '北马其顿',
  'Albania': '阿尔巴尼亚',
  'Bulgaria': '保加利亚',
  'Romania': '罗马尼亚',
  'Moldova': '摩尔多瓦',
  'Finland': '芬兰', 'Suomi': '芬兰',
  'Sweden': '瑞典', 'Sverige': '瑞典',
  'Norway': '挪威', 'Norge': '挪威',
  'Denmark': '丹麦',
  'Iceland': '冰岛',
  'Estonia': '爱沙尼亚',
  'Latvia': '拉脱维亚',
  'Lithuania': '立陶宛',
  'Ireland': '爱尔兰',
  'Malta': '马耳他',
  'Monaco': '摩纳哥',
  'Liechtenstein': '列支敦士登',
  'Andorra': '安道尔',
  'San Marino': '圣马力诺',
  'Vatican': '梵蒂冈',
  'United Kingdom': '英国', 'UK': '英国', 'Great Britain': '英国', 'Britain': '英国',
  // 非洲
  'Egypt': '埃及',
  'Sudan': '苏丹',
  'South Sudan': '南苏丹',
  'Libya': '利比亚',
  'Tunisia': '突尼斯',
  'Algeria': '阿尔及利亚',
  'Morocco': '摩洛哥',
  'Mauritania': '毛里塔尼亚',
  'Nigeria': '尼日利亚',
  'Ghana': '加纳',
  'Senegal': '塞内加尔',
  'Kenya': '肯尼亚',
  'Ethiopia': '埃塞俄比亚',
  'Somalia': '索马里',
  'Tanzania': '坦桑尼亚',
  'Uganda': '乌干达',
  'Rwanda': '卢旺达',
  'Burundi': '布隆迪',
  'Congo': '刚果',
  'Republic of the Congo': '刚果共和国',
  'Democratic Republic of the Congo': '刚果民主共和国',
  'Central African Republic': '中非共和国',
  'Cameroon': '喀麦隆',
  'Equatorial Guinea': '赤道几内亚',
  'Gabon': '加蓬',
  'Angola': '安哥拉',
  'Zambia': '赞比亚',
  'Zimbabwe': '津巴布韦',
  'Mozambique': '莫桑比克',
  'Malawi': '马拉维',
  'Namibia': '纳米比亚',
  'Botswana': '博茨瓦纳',
  'Lesotho': '莱索托',
  'Eswatini': '斯威士兰',
  'South Africa': '南非',
  'Madagascar': '马达加斯加',
  'Mauritius': '毛里求斯',
  'Seychelles': '塞舌尔',
  'Comoros': '科摩罗',
  'Cape Verde': '佛得角',
  'Gambia': '冈比亚',
  'Guinea': '几内亚',
  'Sierra Leone': '塞拉利昂',
  'Liberia': '利比里亚',
  'Burkina Faso': '布基纳法索',
  'Niger': '尼日尔',
  'Chad': '乍得',
  'Guinea-Bissau': '几内亚比绍',
  'Togo': '多哥',
  'Benin': '贝宁',
  'Eritrea': '厄立特里亚',
  'Djibouti': '吉布提',
  'Mali': '马里',
  'Malawi': '马拉维',
  // 美洲
  'United States': '美国', 'United States of America': '美国', 'USA': '美国', 'US': '美国', 'America': '美国',
  'Canada': '加拿大',
  'Mexico': '墨西哥', 'México': '墨西哥',
  'Argentina': '阿根廷',
  'Bolivia': '玻利维亚',
  'Brazil': '巴西', 'Brasil': '巴西',
  'Chile': '智利',
  'Colombia': '哥伦比亚',
  'Costa Rica': '哥斯达黎加',
  'Cuba': '古巴',
  'Dominican Republic': '多米尼加',
  'Ecuador': '厄瓜多尔',
  'El Salvador': '萨尔瓦多',
  'Guatemala': '危地马拉',
  'Haiti': '海地',
  'Honduras': '洪都拉斯',
  'Jamaica': '牙买加',
  'Nicaragua': '尼加拉瓜',
  'Panama': '巴拿马',
  'Paraguay': '巴拉圭',
  'Peru': '秘鲁',
  'Puerto Rico': '波多黎各',
  'Trinidad and Tobago': '特立尼达和多巴哥',
  'Uruguay': '乌拉圭',
  'Venezuela': '委内瑞拉',
  'The Bahamas': '巴哈马',
  'Barbados': '巴巴多斯',
  'Belize': '伯利兹',
  'Guyana': '圭亚那',
  'Suriname': '苏里南',
  'French Guiana': '法属圭亚那',
  // 大洋洲
  'Australia': '澳大利亚',
  'New Zealand': '新西兰',
  'Papua New Guinea': '巴布亚新几内亚',
  'Fiji': '斐济',
  'Samoa': '萨摩亚',
  'Tonga': '汤加',
  'Solomon Islands': '所罗门群岛',
  'Vanuatu': '瓦努阿图',
  'Kiribati': '基里巴斯',
  'Tuvalu': '图瓦卢',
  'Nauru': '瑙鲁',
  // 其他
  'Maurice (Île)': '毛里求斯',
  'Türkiye Cumhuriyeti': '土耳其',
  'السعودية': '沙特阿拉伯', 'المملكة العربية السعودية': '沙特阿拉伯',
  'الإمارات': '阿联酋', 'الإمارات العربية المتحدة': '阿联酋',
  'ایران': '伊朗', 'جمهوری اسلامی ایران': '伊朗',
  'مصر': '埃及',
  'الجزائر': '阿尔及利亚',
  'المغرب': '摩洛哥',
  'تونس': '突尼斯',
  'ليبيا': '利比亚',
  'السودان': '苏丹',
  'الكويت': '科威特',
  'قطر': '卡塔尔',
  'عُمان': '阿曼',
  'البحرين': '巴林',
  'اليمن': '也门',
  'الأردن': '约旦',
  'سوريا': '叙利亚',
  'لبنان': '黎巴嫩',
  'فلسطين': '巴勒斯坦',
  'إسرائيل': '以色列',
  'موريتانيا': '毛里塔尼亚',
  'نيجيريا': '尼日利亚',
  'السنغال': '塞内加尔',
  'كينيا': '肯尼亚',
  'إثيوبيا': '埃塞俄比亚',
  'الصومال': '索马里',
  'تنزانيا': '坦桑尼亚',
  'أوغندا': '乌干达',
  'رواندا': '卢旺达',
  'بوروندي': '布隆迪',
  'الكونغو': '刚果',
  'جمهورية الكونغو': '刚果共和国',
  'جمهورية الكونغو الديمقراطية': '刚果民主共和国',
  'جمهورية افريقيا الوسطى': '中非共和国',
  'الكاميرون': '喀麦隆',
  'غينيا الاستوائية': '赤道几内亚',
  'غابون': '加蓬',
  'أنغولا': '安哥拉',
  'زامبيا': '赞比亚',
  'زيمبابوي': '津巴布韦',
  'موزمبيق': '莫桑比克',
  'مالاوي': '马拉维',
  'ناميبيا': '纳米比亚',
  'بوتسوانا': '博茨瓦纳',
  'ليسوتو': '莱索托',
  'إسواتيني': '斯威士兰',
  'جنوب افريقيا': '南非',
  'مدغشقر': '马达加斯加',
  'موريشيوس': '毛里求斯',
  'سيشل': '塞舌尔',
  'جزر القمر': '科摩罗',
  'كيب فيردي': '佛得角',
  'غامبيا': '冈比亚',
  'غينيا': '几内亚',
  'سيراليون': '塞拉利昂',
  'ليبيريا': '利比里亚',
  'بوركينا فاسو': '布基纳法索',
  'النيجر': '尼日尔',
  'تشاد': '乍得',
  'غينيا بيساو': '几内亚比绍',
  'توجو': '多哥',
  'بنين': '贝宁',
  'إريتريا': '厄立特里亚',
  'جيبوتي': '吉布提',
  'مالي': '马里',
  'الصين': '中国',
  'اليابان': '日本',
  'كوريا الجنوبية': '韩国',
  'كوريا الشمالية': '朝鲜',
  'منغوليا': '蒙古',
  'فيتنام': '越南',
  'تايلاند': '泰国',
  'سنغافورة': '新加坡',
  'ماليزيا': '马来西亚',
  'اندونيسيا': '印度尼西亚',
  'الفلبين': '菲律宾',
  'ميانمار': '缅甸',
  'كمبوديا': '柬埔寨',
  'لاوس': '老挝',
  'الهند': '印度',
  'نيبال': '尼泊尔',
  'سريلانكا': '斯里兰卡',
  'بنجلاديش': '孟加拉国',
  'باكستان': '巴基斯坦',
  'المورديف': '马尔代夫',
  'بوتان': '不丹',
  'أفغانستان': '阿富汗',
  'عراق': '伊拉克',
  'السعودية': '沙特阿拉伯',
  'الإمارات': '阿联酋',
  'الولايات المتحدة': '美国',
  'كندا': '加拿大',
  'المكسيك': '墨西哥',
  'البرازيل': '巴西',
  'الأرجنتين': '阿根廷',
  'تشيلي': '智利',
  'كولومبيا': '哥伦比亚',
  'بيرو': '秘鲁',
  'فنزويلا': '委内瑞拉',
  'كوبا': '古巴',
  'جامايكا': '牙买加',
  'بنما': '巴拿马',
  'الباراغواي': '巴拉غواي',
  'الأوروغواي': '乌拉圭',
  'الاكوادور': '厄瓜多尔',
  'السلفادور': '萨尔瓦多',
  'غواتيمالا': '危地马拉',
  'هندوراس': '洪都拉斯',
  'نيكاراغوا': '尼加拉瓜',
  'كوستاريكا': '哥斯达黎加',
  'بليز': '伯利兹',
  'غيانا': '圭亚那',
  'سورينام': '苏里南',
  'الجمهورية الدومينيكية': '多米尼加',
  'هايتي': '海地',
  'بورتوريكو': '波多黎各',
  'ترينيداد وتوباغو': '特立尼达和多巴哥',
  'الجزر البهاما': '巴哈马',
  'بربادوس': '巴巴多斯',
  'أستراليا': '澳大利亚',
  'نيوزيلندا': '新西兰',
  'بابوا غينيا الجديدة': '巴布亚新几内亚',
  'فيجي': '斐济',
  'ساموا': '萨摩亚',
  'تونغا': '汤加',
  'جزر سليمان': '所罗门群岛',
  'فانواتو': '瓦努阿图',
  'كيريباتي': '基里巴斯',
  'توفالو': '图瓦卢',
  'ناورو': '瑙鲁',
  'البرتغال': '葡萄牙',
  'إسبانيا': '西班牙',
  'إيطاليا': '意大利',
  'ألمانيا': '德国',
  'فرنسا': '法国',
  'المملكة المتحدة': '英国',
  'النرويج': '挪威',
  'السويد': '瑞典',
  'الدنمارك': '丹麦',
  'فنلندا': '芬兰',
  'إيرلندا': '爱尔兰',
  'النمسا': '奥地利',
  'سويسرا': '瑞士',
  'بلجيكا': '比利时',
  'هولندا': '荷兰',
  'اللوكسمبورغ': '卢森堡',
  'مالطا': '马耳他',
  'موناكو': '摩纳哥',
  'ليختنشتاين': '列支敦士登',
  'أندورا': '安道尔',
  'سان مارينو': '圣马力诺',
  'الفاتيكان': '梵蒂冈',
  'بولندا': '波兰',
  'الجمهورية التشيكية': '捷克',
  'سلوفاكيا': '斯洛伐克',
  'المجر': '匈牙利',
  'سلوفينيا': '斯洛文尼亚',
  'كرواتيا': '克罗地亚',
  'البوسنة والهرسك': '波黑',
  'صربيا': '塞尔维亚',
  'الجبل الأسود': '黑山',
  'مقدونيا الشمالية': '北马其顿',
  'ألبانيا': '阿尔巴尼亚',
  'بلغاريا': '保加利亚',
  'رومانيا': '罗马尼亚',
  'مولدوفا': '摩尔多瓦',
  'أوكرانيا': '乌克兰',
  'بيلاروسيا': '白俄罗斯',
  'روسيا': '俄罗斯',
  'كازاخستان': '哈萨克斯坦',
  'أوزبكستان': '乌兹别克斯坦',
  'قيرغيزستان': '吉尔吉斯斯坦',
  'طاجيكستان': '塔吉克斯坦',
  'تركمانستان': '土库曼斯坦',
  'أذربيجان': '阿塞拜疆',
  'أرمينيا': '亚美尼亚',
  'جورجيا': '格鲁吉亚',
  'تركيا': '土耳其',
  'قبرص': '塞浦路س',
}

/** 省/州/大区 翻译（覆盖全球一级行政区） */
const ADMIN1_ZH = {
  // 中国
  '北京市': '北京市', '上海市': '上海市', '天津市': '天津市', '重庆市': '重庆市',
  '香港': '香港', '澳门': '澳门',
  // 英国
  'England': '英格兰', 'Scotland': '苏格兰', 'Wales': '威尔士', 'Northern Ireland': '北爱尔兰',
  'London': '伦敦', 'Greater London': '大伦敦', 'City of London': '伦敦市',
  'Manchester': '曼彻斯特', 'West Midlands': '西米德兰兹', 'Birmingham': '伯明翰',
  'Yorkshire': '约克郡', 'Lancashire': '兰开夏', 'Merseyside': '默西塞德',
  'Edinburgh': '爱丁堡', 'Glasgow': '格拉斯哥', 'Cardiff': '加的夫', 'Belfast': '贝尔法斯特',
  'Cambridge': '剑桥郡', 'Oxford': '牛津郡', 'Nottingham': '诺丁汉郡',
  'Liverpool': '利物浦', 'Bristol': '布里斯托尔', 'Leeds': '利兹',
  // 美国 50 州 + DC
  'Alabama': '亚拉巴马州', 'Alaska': '阿拉斯加州', 'Arizona': '亚利桑那州',
  'Arkansas': '阿肯色州', 'California': '加利福尼亚州', 'Colorado': '科罗拉多州',
  'Connecticut': '康涅狄格州', 'Delaware': '特拉华州', 'Florida': '佛罗里达州',
  'Georgia': '佐治亚州', 'Hawaii': '夏威夷州', 'Idaho': '爱达荷州',
  'Illinois': '伊利诺伊州', 'Indiana': '印第安纳州', 'Iowa': '艾奥瓦州',
  'Kansas': '堪萨斯州', 'Kentucky': '肯塔基州', 'Louisiana': '路易斯安那州',
  'Maine': '缅因州', 'Maryland': '马里兰州', 'Massachusetts': '马萨诸塞州',
  'Michigan': '密歇根州', 'Minnesota': '明尼苏达州', 'Mississippi': '密西西比州',
  'Missouri': '密苏里州', 'Montana': '蒙大拿州', 'Nebraska': '内布拉斯加州',
  'Nevada': '内华达州', 'New Hampshire': '新罕布什尔州', 'New Jersey': '新泽西州',
  'New Mexico': '新墨西哥州', 'New York': '纽约州', 'North Carolina': '北卡罗来纳州',
  'North Dakota': '北达科他州', 'Ohio': '俄亥俄州', 'Oklahoma': '俄克拉何马州',
  'Oregon': '俄勒冈州', 'Pennsylvania': '宾夕法尼亚州', 'Rhode Island': '罗得岛州',
  'South Carolina': '南卡罗来纳州', 'South Dakota': '南达科他州', 'Tennessee': '田纳西州',
  'Texas': '得克萨斯州', 'Utah': '犹他州', 'Vermont': '佛蒙特州',
  'Virginia': '弗吉尼亚州', 'Washington': '华盛顿州', 'West Virginia': '西弗吉尼亚州',
  'Wisconsin': '威斯康星州', 'Wyoming': '怀俄明州',
  'District of Columbia': '华盛顿哥伦比亚特区',
  // 加拿大 10 省 + 3 地区
  'Ontario': '安大略省', 'Quebec': '魁北克省', 'New Brunswick': '新不伦瑞克省',
  'Nova Scotia': '新斯科舍省', 'Prince Edward Island': '爱德华王子岛省',
  'Newfoundland and Labrador': '纽芬兰与拉布拉多省',
  'Manitoba': '马尼托巴省', 'Saskatchewan': '萨斯喀彻温省',
  'Alberta': '阿尔伯塔省', 'British Columbia': '不列颠哥伦比亚省',
  'Yukon': '育空地区', 'Northwest Territories': '西北地区', 'Nunavut': '努纳武特地区',
  // 澳大利亚 6 州 + 2 领地
  'New South Wales': '新南威尔士州', 'Victoria': '维多利亚州',
  'Queensland': '昆士兰州', 'South Australia': '南澳大利亚州',
  'Western Australia': '西澳大利亚州', 'Tasmania': '塔斯马尼亚州',
  'Australian Capital Territory': '澳大利亚首都领地', 'Northern Territory': '北领地',
  // 越南
  'Hà Giang': '河江省', 'Ha Giang': '河江省',
  'Hà Tĩnh': '河静省', 'Ha Tĩnh': '河静省',
  'Tỉnh Hà Giang': '河江省', 'Tỉnh Hà Tĩnh': '河静省',
  'Hà Nội': '河内市', 'Hanoi': '河内市',
  'Thành phố Hồ Chí Minh': '胡志明市', 'Ho Chi Minh City': '胡志明市',
  'Đà Nẵng': '岘港市', 'Da Nang': '岘港市',
  'Hải Phòng': '海防市', 'Hai Phong': '海防市',
  'Cần Thơ': '芹苴市', 'Can Tho': '芹苴市',
  // 阿塞拜疆
  'Imishli District': '伊米什利区', 'Imishli': '伊米什利区',
  'İmişli Rayonu': '伊米什利区',
  'Bakı': '巴库', 'Baku': '巴库',
  // 沙特
  'منطقة حائل': '哈伊勒地区', "Ha'il Region": '哈伊勒地区', 'Hail Region': '哈伊勒地区',
  'منطقة الرياض': '利雅得地区', 'Riyadh Region': '利雅得地区',
  'منطقة مكة': '麦加地区', 'Makkah Region': '麦加地区',
  'منطقة المدينة': '麦地那地区', 'Madinah Region': '麦地那地区',
  // 日本
  'Tōkyō': '东京都', 'Tokyo': '东京都', '東京都': '东京都',
  'Ōsaka': '大阪府', 'Osaka': '大阪府', '大阪府': '大阪府',
  'Kyōto': '京都府', 'Kyoto': '京都府', '京都府': '京都府',
  'Hokkaidō': '北海道', 'Hokkaido': '北海道',
  'Aomori': '青森县', 'Iwate': '岩手县', 'Miyagi': '宫城县',
  'Akita': '秋田县', 'Yamagata': '山形县', 'Fukushima': '福岛县',
  'Ibaraki': '茨城县', 'Tochigi': '枥木县', 'Gunma': '群马县',
  'Saitama': '埼玉县', 'Chiba': '千叶县',
  'Kanagawa': '神奈川县', 'Niigata': '新潟县',
  'Toyama': '富山县', 'Ishikawa': '石川县', 'Fukui': '福井县',
  'Yamanashi': '山梨县', 'Nagano': '长野县',
  'Gifu': '岐阜县', 'Shizuoka': '静冈县', 'Aichi': '爱知县',
  'Mie': '三重县', 'Shiga': '滋贺县',
  'Nara': '奈良县', 'Wakayama': '和歌山县',
  'Tottori': '鸟取县', 'Shimane': '岛根县',
  'Okayama': '冈山县', 'Hiroshima': '广岛县', 'Yamaguchi': '山口县',
  'Tokushima': '德岛县', 'Kagawa': '香川县', 'Ehime': '爱媛县', 'Kōchi': '高知县',
  'Fukuoka': '福冈县', 'Saga': '佐贺县', 'Nagasaki': '长崎县',
  'Kumamoto': '熊本县', 'Ōita': '大分县', 'Miyazaki': '宫崎县', 'Kagoshima': '鹿儿岛县',
  'Okinawa': '冲绳县',
  // 俄罗斯
  'Moskva': '莫斯科州', 'Moscow': '莫斯科',
  'Saint Petersburg': '圣彼得堡', 'Sankt-Peterburg': '圣彼得堡',
  // 法国
  'Île-de-France': '法兰西岛大区',
  'Paris': '巴黎', 'Lyon': '里昂', 'Marseille': '马赛',
  // 德国
  'Bayern': '巴伐利亚州', 'Berlin': '柏林', 'München': '慕尼黑', 'Hamburg': '汉堡',
  'Niedersachsen': '下萨克森州', 'Nordrhein-Westfalen': '北莱茵-威斯特法伦州',
  'Baden-Württemberg': '巴登-符腾堡州', 'Hessen': '黑森州',
  'Rheinland-Pfalz': '莱茵兰-普法尔茨州', 'Schleswig-Holstein': '石勒苏益格-荷尔斯泰因州',
  'Brandenburg': '勃兰登堡州', 'Mecklenburg-Vorpommern': '梅克伦堡-前波美拉尼亚州',
  'Sachsen': '萨克森州', 'Sachsen-Anhalt': '萨克森-安哈尔特州',
  'Thüringen': '图林根州', 'Saarland': '萨尔兰州',
  'Bremen': '不来梅州', 'Stuttgart': '斯图加特', 'Frankfurt': '法兰克福',
  'Köln': '科隆', 'Düsseldorf': '杜塞尔多夫', 'Leipzig': '莱比锡',
  'Dortmund': '多特蒙德', 'Essen': '埃森', 'Hanover': '汉诺威',
  'Dresden': '德累斯顿', 'Nuremberg': '纽伦堡',
  // 沙特补充行政区
  'القصيم': '盖西姆省', 'محافظة وادي الدواسر': '瓦迪杜瓦塞尔省',
  'محافظة القويعيه': '盖伊耶省', 'محافظة الحريق': '哈里克省',
  'المنطقة الشرقية': '东部地区', 'عسير': '阿西尔省',
  'تبوك': '泰布克省', 'الجوف': '焦夫省',
  'الحدود الشمالية': '北部边境省', 'نجران': '奈季兰省',
  'الباحة': '巴哈省', 'المملكة العربية السعودية': '沙特阿拉伯',
  // 西班牙
  'Cataluña': '加泰罗尼亚', 'Barcelona': '巴塞罗那', 'Madrid': '马德里',
  // 意大利
  'Roma': '罗马', 'Milano': '米兰', 'Lazio': '拉齐奥大区',
  // 荷兰
  'Noord-Holland': '北荷兰省', 'Zuid-Holland': '南荷兰省', 'Amsterdam': '阿姆斯特丹',
  // 非洲
  'Kongo Central': '下刚果省', 'Kinshasa': '金沙萨',
  'République démocratique du Congo': '刚果民主共和国',
  'République du Congo': '刚果共和国',
  'Province de Kinshasa': '金沙萨省',
  // 南美
  'São Paulo': '圣保罗州', 'Sao Paulo': '圣保罗州',
  'Buenos Aires': '布宜诺斯艾利斯',
}

/** 城市/区名翻译（覆盖全球主要城市） */
const CITY_ZH = {
  // 沙特
  'حائل': '哈伊勒', 'Hail': '哈伊勒', "Ha'il": '哈伊勒',
  'الرياض': '利雅得', 'Riyadh': '利雅得',
  'مكة': '麦加', 'Makkah': '麦加', 'Mecca': '麦加',
  'المدينة': '麦地那', 'Madinah': '麦地那', 'Medina': '麦地那',
  'جدة': '吉达', 'Jeddah': '吉达',
  // 越南
  'Hà Giang': '河江', 'Ha Giang': '河江',
  'Hà Tĩnh': '河静', 'Ha Tĩnh': '河静',
  'Hà Nội': '河内', 'Hanoi': '河内',
  'Thành phố Hồ Chí Minh': '胡志明市', 'Ho Chi Minh City': '胡志明市',
  'Đà Nẵng': '岘港', 'Da Nang': '岘港',
  'Hải Phòng': '海防', 'Hai Phong': '海防',
  'Cần Thơ': '芹苴', 'Can Tho': '芹苴',
  'Huế': '顺化', 'Hue': '顺化',
  'Nha Trang': '芽庄',
  'Đà Lạt': '大叻', 'Da Lat': '大叻',
  'Vũng Tàu': '头顿', 'Vung Tau': '头顿',
  // 阿塞拜疆
  'İmişli': '伊米什利', 'Imishli': '伊米什利',
  'Bakı': '巴库', 'Baku': '巴库',
  'Ganja': '占贾', 'Sumgait': '苏姆盖特',
  // 英国
  'London': '伦敦', 'City of London': '伦敦市', 'Westminster': '威斯敏斯特',
  'Manchester': '曼彻斯特', 'Birmingham': '伯明翰', 'Liverpool': '利物浦',
  'Leeds': '利兹', 'Sheffield': '谢菲尔德', 'Bristol': '布里斯托尔',
  'Edinburgh': '爱丁堡', 'Glasgow': '格拉斯哥', 'Belfast': '贝尔法斯特',
  'Cambridge': '剑桥', 'Oxford': '牛津', 'Nottingham': '诺丁汉',
  'Brighton': '布莱顿', 'Newcastle': '纽卡斯尔', 'Southampton': '南安普敦',
  // 日本
  '東京': '东京', 'Tokyo': '东京', 'Tōkyō': '东京',
  '大阪': '大阪', 'Osaka': '大阪',
  '京都': '京都', 'Kyoto': '京都',
  '札幌': '札幌', 'Sapporo': '札幌',
  '福岡': '福冈', 'Fukuoka': '福冈',
  '横浜': '横滨', 'Yokohama': '横滨',
  '名古屋': '名古屋', 'Nagoya': '名古屋',
  '八王子市': '八王子市', 'Hachiōji': '八王子市', 'Hachioji': '八王子市',
  '練馬': '练马', 'Nerima': '练马',
  '府中市': '府中市', 'Fuchū': '府中市', 'Fuchu': '府中市',
  '日野市': '日野市', 'Hino': '日野市',
  // 韩国
  '서울': '首尔', 'Seoul': '首尔',
  '부산': '釜山', 'Busan': '釜山',
  '인천': '仁川', 'Incheon': '仁川',
  // 美国
  'New York': '纽约', 'Los Angeles': '洛杉矶', 'San Francisco': '旧金山',
  'Chicago': '芝加哥', 'Boston': '波士顿', 'Seattle': '西雅图',
  'Washington': '华盛顿', 'Miami': '迈阿密', 'Houston': '休斯顿',
  'Philadelphia': '费城', 'Phoenix': '菲尼克斯', 'San Diego': '圣迭戈',
  'Dallas': '达拉斯', 'San Antonio': '圣安东尼奥', 'Austin': '奥斯汀',
  'Jacksonville': '杰克逊维尔', 'Fort Worth': '沃斯堡', 'Columbus': '哥伦布',
  'Charlotte': '夏洛特', 'Indianapolis': '印第安纳波利斯',
  'San Jose': '圣何塞', 'Nashville': '纳什维尔',
  'Portland': '波特兰', 'Denver': '丹佛',
  // 加拿大
  'Vancouver': '温哥华', 'Toronto': '多伦多', 'Montreal': '蒙特利尔',
  'Calgary': '卡尔加里', 'Ottawa': '渥太华', 'Edmonton': '埃德蒙顿',
  'Winnipeg': '温尼伯', 'Quebec City': '魁北克市', 'Hamilton': '哈密尔顿',
  // 澳大利亚
  'Sydney': '悉尼', 'Melbourne': '墨尔本', 'Brisbane': '布里斯班',
  'Perth': '珀斯', 'Adelaide': '阿德莱德', 'Gold Coast': '黄金海岸',
  'Canberra': '堪培拉', 'Hobart': '霍巴特',
  // 新西兰
  'Auckland': '奥克兰', 'Wellington': '惠灵顿', 'Christchurch': '克赖斯特彻奇',
  // 东南亚
  'Bangkok': '曼谷', 'Chiang Mai': '清迈', 'Phuket': '普吉',
  'Singapore': '新加坡', 'Kuala Lumpur': '吉隆坡', 'Penang': '槟城',
  'Jakarta': '雅加达', 'Bali': '巴厘岛', 'Manila': '马尼拉',
  'Hanoi': '河内', 'Ho Chi Minh City': '胡志明市',
  'Dili': '帝力',
  // 南亚
  'Mumbai': '孟买', 'मुम्बई': '孟买', 'पवई': '孟买',
  'New Delhi': '新德里', 'Delhi': '德里',
  'Kolkata': '加尔各答', 'Bengaluru': '班加罗尔', 'Bangalore': '班加罗尔',
  'Colombo': '科伦坡', 'Kathmandu': '加德满都',
  'Dubai': '迪拜', 'Abu Dhabi': '阿布扎比', 'Doha': '多哈',
  'Karachi': '卡拉奇', 'Lahore': '拉合尔',
  'Dhaka': '达卡', 'Islamabad': '伊斯兰堡',
  'Kabul': '喀布尔', 'Tehran': '德黑兰',
  'Baghdad': '巴格达', 'Riyadh': '利雅得',
  // 欧洲
  'Paris': '巴黎', 'Lyon': '里昂', 'Marseille': '马赛', 'Nice': '尼斯',
  'Berlin': '柏林', 'Munich': '慕尼黑', 'München': '慕尼黑', 'Hamburg': '汉堡',
  'Frankfurt': '法兰克福', 'Cologne': '科隆',
  'Roma': '罗马', 'Rome': '罗马', 'Milano': '米兰', 'Milan': '米兰',
  'Venezia': '威尼斯', 'Venice': '威尼斯',
  'Madrid': '马德里', 'Barcelona': '巴塞罗那', 'Valencia': '瓦伦西亚',
  'Lisbon': '里斯本', 'Porto': '波尔图',
  'Amsterdam': '阿姆斯特丹', 'Vienna': '维也纳', 'Prague': '布拉格',
  'Budapest': '布达佩斯', 'Warsaw': '华沙', 'Stockholm': '斯德哥尔摩',
  'Copenhagen': '哥本哈根', 'Oslo': '奥斯陆', 'Helsinki': '赫尔辛基',
  'Zurich': '苏黎世', 'Geneva': '日内瓦', 'Athens': '雅典',
  'Brussels': '布鲁塞尔', 'Dublin': '都柏林', 'Reykjavik': '雷克雅未克',
  'Rotterdam': '鹿特丹', 'The Hague': '海牙',
  'Bucharest': '布加勒斯特', 'Sofia': '索非亚', 'Belgrade': '贝尔格莱德',
  'Ljubljana': '卢布尔雅那', 'Zagreb': '萨格勒布',
  // 俄/非/拉美
  'Moscow': '莫斯科', 'Saint Petersburg': '圣彼得堡',
  'Kyiv': '基辅', 'Kiev': '基辅',
  'Cairo': '开罗', 'القاهرة': '开罗',
  'Cape Town': '开普敦', 'Johannesburg': '约翰内斯堡',
  'Lagos': '拉各斯', 'Nairobi': '内罗毕', 'Casablanca': '卡萨布兰卡',
  'Kinshasa': '金沙萨', 'M\'Banza Kongo': '姆班扎刚果',
  'Boma': '博马', 'Luvaka': '卢瓦卡', 'Inga': '英加', 'Luozi': '卢奥齐',
  'Luanda': '罗安达', 'Maputo': '马普托', 'Harare': '哈拉雷',
  'Lusaka': '卢萨卡', 'Gaborone': '哈博罗内',
  'Cape Town': '开普敦', 'Durban': '德班', 'Pretoria': '比勒陀利亚',
  'São Paulo': '圣保罗', 'Sao Paulo': '圣保罗',
  'Rio de Janeiro': '里约热内卢', 'Buenos Aires': '布宜诺斯艾利斯',
  'Lima': '利马', 'Santiago': '圣地亚哥',
  'Bogotá': '波哥大', 'Bogota': '波哥大',
  'Caracas': '加拉加斯', 'Quito': '基多',
  'La Paz': '拉巴斯', 'Asunción': '亚松森',
  'Montevideo': '蒙得维的亚',
  'Mexico City': '墨西哥城', 'Ciudad de México': '墨西哥城',
  'Havana': '哈瓦那', 'Panama City': '巴拿马城',
  'San José': '圣何塞', 'San Juan': '圣胡安',
  'Brasília': '巴西利亚', 'Brasilia': '巴西利亚',
  // 波兰
  'Hażlach': '哈伊拉赫', 'Hazlach': '哈伊拉赫',
  // 其他常见
  'Islamabad': '伊斯兰堡', 'Ankara': '安卡拉',
  'Tashkent': '塔什干', 'Almaty': '阿拉木图',
  'Ashgabat': '阿什哈巴德', 'Bishkek': '比什凯克',
  'Dushanbe': '杜尚别',
  // 挪威
  'Blindern': '布林德恩', 'Lysaker': '吕萨克', 'Akershus': '阿克什胡斯',
  // 芬兰
  'Uusimaa': '新地区', 'Vantaa': '万塔', 'Otaniemi': '奥塔涅米',
  'Tuusula': '图苏拉', 'Järvenpää': '耶尔文佩',
  // 冰岛
  'Reykjavík': '雷克雅未克', 'Höfuðborgarsvæði': '首都地区',
  'Ísland': '冰岛', 'Saurbær': '索尔拜尔', 'Garðabær': '加扎拜尔',
  'Hafnarfjörður': '哈布纳菲厄泽', 'Kópavogur': '科帕沃于尔',
  // 瑞典
  'Stockholm': '斯德哥尔摩', 'Göteborg': '哥德堡', 'Malmö': '马尔默',
  'Uppsala': '乌普萨拉', 'Västerås': '韦斯特罗斯',
  // 丹麦
  'København': '哥本哈根', 'Aarhus': '奥胡斯', 'Odense': '欧登塞',
  // 挪威补充
  'Oslo': '奥斯陆', 'Bergen': '卑尔根', 'Trondheim': '特隆赫姆',
  'Stavanger': '斯塔万格', 'Drammen': '德拉门',
  // 德国
  'Osloß': '奥斯洛斯', 'Niedersachsen': '下萨克森',
  'Nordrhein-Westfalen': '北莱茵-威斯特法伦', 'Bayern': '巴伐利亚',
  'Hamburg': '汉堡', 'München': '慕尼黑', 'Köln': '科隆',
  'Frankfurt': '法兰克福', 'Stuttgart': '斯图加特', 'Düsseldorf': '杜塞尔多夫',
  'Leipzig': '莱比锡', 'Dortmund': '多特蒙德', 'Essen': '埃森',
  'Bremen': '不来梅', 'Hanover': '汉诺威', 'Dresden': '德累斯顿',
  // 沙特阿拉伯行政区
  'القصيم': '盖西姆', 'محافظة وادي الدواسر': '瓦迪杜瓦塞尔省',
  'محافظة القويعيه': '盖伊耶省', 'محافظة الحريق': '哈里克省',
  // 日本补充
  '府中市': '府中市', '日野市': '日野市', '稲城市': '稻城市',
  '多摩市': '多摩市', '八王子市': '八王子市', '立川市': '立川市',
  '青梅市': '青梅市', '昭岛市': '昭岛市', '调布市': '调布市',
  '町田市': '町田市', '小金井市': '小金井市', '小平市': '小平市',
  '东大阪市': '东大阪市', '堺市': '堺市', '岸和田市': '岸和田市',
  '豊中市': '丰中市', '吹田市': '吹田市', '茨木市': '茨木市',
  '高槻市': '高槻市', '枚方市': '枚方市', '寝屋川市': '寝屋川市',
}

/**
 * 统一地名翻译：城市 → 省州 → 国家 逐级回退
 * 对带行政区后缀的名称（如 "Province of X"）做清洗后再查
 */
export function translateGeoName(name) {
  if (!name) return ''
  const raw = String(name).trim()
  if (!raw) return ''

  // 精确匹配
  if (CITY_ZH[raw]) return CITY_ZH[raw]
  if (ADMIN1_ZH[raw]) return ADMIN1_ZH[raw]
  if (COUNTRY_ZH[raw]) return COUNTRY_ZH[raw]

  // 兜底：去掉常见行政区后缀后再查
  const sanitized = raw
    .replace(/^(Province|State|Region|City|District|Prefecture|Governorate|Wilaya)\s+(of\s+)?/i, '')
    .replace(/\s+(Province|State|Region|City|District|Prefecture|Governorate|Wilaya)$/i, '')
    .trim()

  if (sanitized && sanitized !== raw) {
    if (CITY_ZH[sanitized]) return CITY_ZH[sanitized]
    if (ADMIN1_ZH[sanitized]) return ADMIN1_ZH[sanitized]
    if (COUNTRY_ZH[sanitized]) return COUNTRY_ZH[sanitized]
  }

  return raw
}

/** 拼接「原名 + (中文翻译)」用于 UI 展示，确保所有条目都带中文翻译 */
export function formatGeoWithZh(name) {
  if (!name) return ''
  const raw = String(name).trim()
  const zh = translateGeoName(raw)
  if (!zh) return raw
  return `${raw} (${zh})`
}